/* Generated by Yosys 0.36+58 (git sha1 ea7818d31, c++ 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

(* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:1.1-16.10" *)
module counter(clk, rst, enable, \bits[0] , \bits[1] , \bits[2] , \bits[3] , \bits[4] , \bits[5] , \bits[6] , \bits[7] );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire ins_00_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire ins_01_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire ins_02_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire ins_03_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire ins_04_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire ins_05_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire ins_06_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:12.15-12.23|/opt/OpenLane/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire ins_07_;
  wire ins_08_;
  wire ins_09_;
  wire ins_10_;
  wire ins_11_;
  wire ins_12_;
  wire ins_13_;
  wire ins_14_;
  wire ins_15_;
  wire ins_16_;
  wire ins_17_;
  wire ins_18_;
  wire ins_19_;
  wire ins_20_;
  wire ins_21_;
  wire ins_22_;
  wire ins_23_;
  wire ins_24_;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[0] ;
  wire \bits[0] ;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[1] ;
  wire \bits[1] ;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[2] ;
  wire \bits[2] ;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[3] ;
  wire \bits[3] ;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[4] ;
  wire \bits[4] ;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[5] ;
  wire \bits[5] ;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[6] ;
  wire \bits[6] ;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:5.20-5.24" *)
  output \bits[7] ;
  wire \bits[7] ;
  (* CLASS = "clock" *)
  (* CLOCK_SIGNAL = "yes" *)
  (* IS_EXPLICIT = 32'd1 *)
  (* NAME = "clk" *)
  (* PERIOD = "10.000000" *)
  (* SOURCE_WIRES = "clk" *)
  (* WAVEFORM = "0.000000 5.000000" *)
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:4.9-4.15" *)
  input enable;
  wire enable;
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:3.9-3.12" *)
  input rst;
  wire rst;
  INVD1 ins_25_ (
    .i(rst),
    .z(ins_08_)
  );
  INVD1 ins_26_ (
    .i(\bits[0] ),
    .z(ins_00_)
  );
  INVD1 ins_27_ (
    .i(\bits[4] ),
    .z(ins_16_)
  );
  INVD1 ins_28_ (
    .i(\bits[5] ),
    .z(ins_17_)
  );
  INVD1 ins_29_ (
    .i(\bits[6] ),
    .z(ins_18_)
  );
  ND2D1 ins_30_ (
    .a1(\bits[0] ),
    .a2(\bits[1] ),
    .zn(ins_19_)
  );
  ND3D1 ins_31_ (
    .a1(\bits[0] ),
    .a2(\bits[1] ),
    .a3(\bits[2] ),
    .zn(ins_20_)
  );
  ND4D1 ins_32_ (
    .a1(\bits[0] ),
    .a2(\bits[3] ),
    .a3(\bits[1] ),
    .a4(\bits[2] ),
    .zn(ins_21_)
  );
  XNR2D1 ins_33_ (
    .a1(\bits[3] ),
    .a2(ins_20_),
    .zn(ins_03_)
  );
  NR2D1 ins_34_ (
    .a1(ins_16_),
    .a2(ins_21_),
    .zn(ins_22_)
  );
  XNR2D1 ins_35_ (
    .a1(\bits[4] ),
    .a2(ins_21_),
    .zn(ins_04_)
  );
  NR3D1 ins_36_ (
    .a1(ins_16_),
    .a2(ins_17_),
    .a3(ins_21_),
    .zn(ins_23_)
  );
  XNR2D1 ins_37_ (
    .a1(ins_17_),
    .a2(ins_22_),
    .zn(ins_05_)
  );
  NR4D1 ins_38_ (
    .a1(ins_16_),
    .a2(ins_17_),
    .a3(ins_18_),
    .a4(ins_21_),
    .zn(ins_24_)
  );
  XNR2D1 ins_39_ (
    .a1(ins_18_),
    .a2(ins_23_),
    .zn(ins_06_)
  );
  XOR2D1 ins_40_ (
    .a1(\bits[7] ),
    .a2(ins_24_),
    .z(ins_07_)
  );
  XOR2D1 ins_41_ (
    .a1(\bits[0] ),
    .a2(\bits[1] ),
    .z(ins_01_)
  );
  XNR2D1 ins_42_ (
    .a1(\bits[2] ),
    .a2(ins_19_),
    .zn(ins_02_)
  );
  INVD1 ins_43_ (
    .i(rst),
    .z(ins_09_)
  );
  INVD1 ins_44_ (
    .i(rst),
    .z(ins_10_)
  );
  INVD1 ins_45_ (
    .i(rst),
    .z(ins_11_)
  );
  INVD1 ins_46_ (
    .i(rst),
    .z(ins_12_)
  );
  INVD1 ins_47_ (
    .i(rst),
    .z(ins_13_)
  );
  INVD1 ins_48_ (
    .i(rst),
    .z(ins_14_)
  );
  INVD1 ins_49_ (
    .i(rst),
    .z(ins_15_)
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_50_ (
    .cdn(ins_08_),
    .cp(clk),
    .d(ins_00_),
    .q(\bits[0] )
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_51_ (
    .cdn(ins_09_),
    .cp(clk),
    .d(ins_01_),
    .q(\bits[1] )
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_52_ (
    .cdn(ins_10_),
    .cp(clk),
    .d(ins_02_),
    .q(\bits[2] )
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_53_ (
    .cdn(ins_11_),
    .cp(clk),
    .d(ins_03_),
    .q(\bits[3] )
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_54_ (
    .cdn(ins_12_),
    .cp(clk),
    .d(ins_04_),
    .q(\bits[4] )
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_55_ (
    .cdn(ins_13_),
    .cp(clk),
    .d(ins_05_),
    .q(\bits[5] )
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_56_ (
    .cdn(ins_14_),
    .cp(clk),
    .d(ins_06_),
    .q(\bits[6] )
  );
  (* src = "/home/duran/Documents/orule1um/orule1um_verilog2gds/src/counter.v:8.3-14.6" *)
  DFCNQD1 ins_57_ (
    .cdn(ins_15_),
    .cp(clk),
    .d(ins_07_),
    .q(\bits[7] )
  );
endmodule
